// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlcgen

import (
	"context"

	"github.com/gofrs/uuid"
)

const updateIdentityProviderID = `-- name: UpdateIdentityProviderID :exec
UPDATE auth.identities SET provider_id = $1 WHERE id = $2
`

type UpdateIdentityProviderIDParams struct {
	ProviderID string
	ID         uuid.UUID
}

// Uses a raw UPDATE rather than the ORM's primary-key update because
// Identity's primary key is (provider, id), not provider_id.
func (q *Queries) UpdateIdentityProviderID(ctx context.Context, arg UpdateIdentityProviderIDParams) error {
	_, err := q.db.ExecContext(ctx, updateIdentityProviderID, arg.ProviderID, arg.ID)
	return err
}
