// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/gofrs/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthAalLevel string

const (
	AuthAalLevelAal1 AuthAalLevel = "aal1"
	AuthAalLevelAal2 AuthAalLevel = "aal2"
	AuthAalLevelAal3 AuthAalLevel = "aal3"
)

func (e *AuthAalLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthAalLevel(s)
	case string:
		*e = AuthAalLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthAalLevel: %T", src)
	}
	return nil
}

type NullAuthAalLevel struct {
	AuthAalLevel AuthAalLevel
	Valid        bool // Valid is true if AuthAalLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthAalLevel) Scan(value interface{}) error {
	if value == nil {
		ns.AuthAalLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthAalLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthAalLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthAalLevel), nil
}

type AuthCodeChallengeMethod string

const (
	AuthCodeChallengeMethodS256  AuthCodeChallengeMethod = "s256"
	AuthCodeChallengeMethodPlain AuthCodeChallengeMethod = "plain"
)

func (e *AuthCodeChallengeMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthCodeChallengeMethod(s)
	case string:
		*e = AuthCodeChallengeMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthCodeChallengeMethod: %T", src)
	}
	return nil
}

type NullAuthCodeChallengeMethod struct {
	AuthCodeChallengeMethod AuthCodeChallengeMethod
	Valid                   bool // Valid is true if AuthCodeChallengeMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthCodeChallengeMethod) Scan(value interface{}) error {
	if value == nil {
		ns.AuthCodeChallengeMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthCodeChallengeMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthCodeChallengeMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthCodeChallengeMethod), nil
}

type AuthFactorStatus string

const (
	AuthFactorStatusUnverified AuthFactorStatus = "unverified"
	AuthFactorStatusVerified   AuthFactorStatus = "verified"
)

func (e *AuthFactorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthFactorStatus(s)
	case string:
		*e = AuthFactorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthFactorStatus: %T", src)
	}
	return nil
}

type NullAuthFactorStatus struct {
	AuthFactorStatus AuthFactorStatus
	Valid            bool // Valid is true if AuthFactorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthFactorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuthFactorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthFactorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthFactorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthFactorStatus), nil
}

type AuthFactorType string

const (
	AuthFactorTypeTotp         AuthFactorType = "totp"
	AuthFactorTypeWebauthn     AuthFactorType = "webauthn"
	AuthFactorTypePhone        AuthFactorType = "phone"
	AuthFactorTypeRecoveryCode AuthFactorType = "recovery_code"
)

func (e *AuthFactorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthFactorType(s)
	case string:
		*e = AuthFactorType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthFactorType: %T", src)
	}
	return nil
}

type NullAuthFactorType struct {
	AuthFactorType AuthFactorType
	Valid          bool // Valid is true if AuthFactorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthFactorType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthFactorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthFactorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthFactorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthFactorType), nil
}

type AuthOauthAuthorizationStatus string

const (
	AuthOauthAuthorizationStatusPending  AuthOauthAuthorizationStatus = "pending"
	AuthOauthAuthorizationStatusApproved AuthOauthAuthorizationStatus = "approved"
	AuthOauthAuthorizationStatusDenied   AuthOauthAuthorizationStatus = "denied"
	AuthOauthAuthorizationStatusExpired  AuthOauthAuthorizationStatus = "expired"
)

func (e *AuthOauthAuthorizationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOauthAuthorizationStatus(s)
	case string:
		*e = AuthOauthAuthorizationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOauthAuthorizationStatus: %T", src)
	}
	return nil
}

type NullAuthOauthAuthorizationStatus struct {
	AuthOauthAuthorizationStatus AuthOauthAuthorizationStatus
	Valid                        bool // Valid is true if AuthOauthAuthorizationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOauthAuthorizationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOauthAuthorizationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOauthAuthorizationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOauthAuthorizationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOauthAuthorizationStatus), nil
}

type AuthOauthClientType string

const (
	AuthOauthClientTypePublic       AuthOauthClientType = "public"
	AuthOauthClientTypeConfidential AuthOauthClientType = "confidential"
)

func (e *AuthOauthClientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOauthClientType(s)
	case string:
		*e = AuthOauthClientType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOauthClientType: %T", src)
	}
	return nil
}

type NullAuthOauthClientType struct {
	AuthOauthClientType AuthOauthClientType
	Valid               bool // Valid is true if AuthOauthClientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOauthClientType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOauthClientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOauthClientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOauthClientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOauthClientType), nil
}

type AuthOauthRegistrationType string

const (
	AuthOauthRegistrationTypeDynamic AuthOauthRegistrationType = "dynamic"
	AuthOauthRegistrationTypeManual  AuthOauthRegistrationType = "manual"
)

func (e *AuthOauthRegistrationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOauthRegistrationType(s)
	case string:
		*e = AuthOauthRegistrationType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOauthRegistrationType: %T", src)
	}
	return nil
}

type NullAuthOauthRegistrationType struct {
	AuthOauthRegistrationType AuthOauthRegistrationType
	Valid                     bool // Valid is true if AuthOauthRegistrationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOauthRegistrationType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOauthRegistrationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOauthRegistrationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOauthRegistrationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOauthRegistrationType), nil
}

type AuthOauthResponseType string

const (
	AuthOauthResponseTypeCode AuthOauthResponseType = "code"
)

func (e *AuthOauthResponseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOauthResponseType(s)
	case string:
		*e = AuthOauthResponseType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOauthResponseType: %T", src)
	}
	return nil
}

type NullAuthOauthResponseType struct {
	AuthOauthResponseType AuthOauthResponseType
	Valid                 bool // Valid is true if AuthOauthResponseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOauthResponseType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOauthResponseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOauthResponseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOauthResponseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOauthResponseType), nil
}

type AuthOneTimeTokenType string

const (
	AuthOneTimeTokenTypeConfirmationToken       AuthOneTimeTokenType = "confirmation_token"
	AuthOneTimeTokenTypeReauthenticationToken   AuthOneTimeTokenType = "reauthentication_token"
	AuthOneTimeTokenTypeRecoveryToken           AuthOneTimeTokenType = "recovery_token"
	AuthOneTimeTokenTypeEmailChangeTokenNew     AuthOneTimeTokenType = "email_change_token_new"
	AuthOneTimeTokenTypeEmailChangeTokenCurrent AuthOneTimeTokenType = "email_change_token_current"
	AuthOneTimeTokenTypePhoneChangeToken        AuthOneTimeTokenType = "phone_change_token"
)

func (e *AuthOneTimeTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthOneTimeTokenType(s)
	case string:
		*e = AuthOneTimeTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthOneTimeTokenType: %T", src)
	}
	return nil
}

type NullAuthOneTimeTokenType struct {
	AuthOneTimeTokenType AuthOneTimeTokenType
	Valid                bool // Valid is true if AuthOneTimeTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthOneTimeTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthOneTimeTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthOneTimeTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthOneTimeTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthOneTimeTokenType), nil
}

// Auth: Audit trail for user actions.
type AuthAuditLogEntry struct {
	InstanceID uuid.NullUUID
	ID         uuid.UUID
	Payload    pqtype.NullRawMessage
	CreatedAt  sql.NullTime
	IpAddress  string
}

type AuthCustomOauthProvider struct {
	ID                    uuid.UUID
	ProviderType          string
	Identifier            string
	Name                  string
	ClientID              string
	ClientSecret          string
	AcceptableClientIds   []string
	Scopes                []string
	PkceEnabled           bool
	AttributeMapping      json.RawMessage
	AuthorizationParams   json.RawMessage
	Enabled               bool
	EmailOptional         bool
	Issuer                sql.NullString
	DiscoveryUrl          sql.NullString
	SkipNonceCheck        bool
	CachedDiscovery       pqtype.NullRawMessage
	DiscoveryCachedAt     sql.NullTime
	AuthorizationUrl      sql.NullString
	TokenUrl              sql.NullString
	UserinfoUrl           sql.NullString
	JwksUri               sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
	CustomClaimsAllowlist []string
}

// Stores metadata for all OAuth/SSO login flows
type AuthFlowState struct {
	ID                   uuid.UUID
	UserID               uuid.NullUUID
	AuthCode             sql.NullString
	CodeChallengeMethod  NullAuthCodeChallengeMethod
	CodeChallenge        sql.NullString
	ProviderType         string
	ProviderAccessToken  sql.NullString
	ProviderRefreshToken sql.NullString
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	AuthenticationMethod string
	AuthCodeIssuedAt     sql.NullTime
	InviteToken          sql.NullString
	Referrer             sql.NullString
	OauthClientStateID   uuid.NullUUID
	LinkingTargetID      uuid.NullUUID
	EmailOptional        bool
}

// Auth: Stores identities associated to a user.
type AuthIdentity struct {
	ProviderID   string
	UserID       uuid.UUID
	IdentityData json.RawMessage
	Provider     string
	LastSignInAt sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	// Auth: Email is a generated column that references the optional email property in the identity_data
	Email sql.NullString
	ID    uuid.UUID
}

// Auth: Manages users across multiple sites.
type AuthInstance struct {
	ID            uuid.UUID
	Uuid          uuid.NullUUID
	RawBaseConfig sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

// auth: stores authenticator method reference claims for multi factor authentication
type AuthMfaAmrClaim struct {
	SessionID            uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	AuthenticationMethod string
	ID                   uuid.UUID
}

// auth: stores metadata about challenge requests made
type AuthMfaChallenge struct {
	ID                  uuid.UUID
	FactorID            uuid.UUID
	CreatedAt           time.Time
	VerifiedAt          sql.NullTime
	IpAddress           pqtype.Inet
	OtpCode             sql.NullString
	WebAuthnSessionData pqtype.NullRawMessage
}

// auth: stores metadata about factors
type AuthMfaFactor struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	FriendlyName       sql.NullString
	FactorType         AuthFactorType
	Status             AuthFactorStatus
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Secret             sql.NullString
	Phone              sql.NullString
	LastChallengedAt   sql.NullTime
	WebAuthnCredential pqtype.NullRawMessage
	WebAuthnAaguid     uuid.NullUUID
	// Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
	LastWebauthnChallengeData pqtype.NullRawMessage
}

type AuthMfaRecoveryCode struct {
	ID                   uuid.UUID
	MfaRecoveryCodeSetID uuid.UUID
	CodeHash             string
	ConsumedAt           sql.NullTime
	CreatedAt            time.Time
}

type AuthMfaRecoveryCodeSet struct {
	ID                      uuid.UUID
	UserID                  uuid.UUID
	MfaFactorID             uuid.UUID
	FailedVerificationCount int32
	VerificationLockedUntil sql.NullTime
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type AuthOauthAuthorization struct {
	ID                  uuid.UUID
	AuthorizationID     string
	ClientID            uuid.UUID
	UserID              uuid.NullUUID
	RedirectUri         string
	Scope               string
	State               sql.NullString
	Resource            sql.NullString
	CodeChallenge       sql.NullString
	CodeChallengeMethod NullAuthCodeChallengeMethod
	ResponseType        AuthOauthResponseType
	Status              AuthOauthAuthorizationStatus
	AuthorizationCode   sql.NullString
	CreatedAt           time.Time
	ExpiresAt           time.Time
	ApprovedAt          sql.NullTime
	Nonce               sql.NullString
}

type AuthOauthClient struct {
	ID                      uuid.UUID
	ClientSecretHash        sql.NullString
	RegistrationType        AuthOauthRegistrationType
	RedirectUris            string
	GrantTypes              string
	ClientName              sql.NullString
	ClientUri               sql.NullString
	LogoUri                 sql.NullString
	CreatedAt               time.Time
	UpdatedAt               time.Time
	DeletedAt               sql.NullTime
	ClientType              AuthOauthClientType
	TokenEndpointAuthMethod string
}

// Stores OAuth states for third-party provider authentication flows where Supabase acts as the OAuth client.
type AuthOauthClientState struct {
	ID           uuid.UUID
	ProviderType string
	CodeVerifier sql.NullString
	CreatedAt    time.Time
}

type AuthOauthConsent struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ClientID  uuid.UUID
	Scopes    string
	GrantedAt time.Time
	RevokedAt sql.NullTime
}

type AuthOneTimeToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenType AuthOneTimeTokenType
	TokenHash string
	RelatesTo string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
}

// Auth: Store of tokens used to refresh JWT tokens once they expire.
type AuthRefreshToken struct {
	InstanceID uuid.NullUUID
	ID         int64
	Token      sql.NullString
	UserID     sql.NullString
	Revoked    sql.NullBool
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Parent     sql.NullString
	SessionID  uuid.NullUUID
}

// Auth: Manages SAML Identity Provider connections.
type AuthSamlProvider struct {
	ID               uuid.UUID
	SsoProviderID    uuid.UUID
	EntityID         string
	MetadataXml      string
	MetadataUrl      sql.NullString
	AttributeMapping pqtype.NullRawMessage
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	NameIDFormat     sql.NullString
}

// Auth: Contains SAML Relay State information for each Service Provider initiated login.
type AuthSamlRelayState struct {
	ID            uuid.UUID
	SsoProviderID uuid.UUID
	RequestID     string
	ForEmail      sql.NullString
	RedirectTo    sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	FlowStateID   uuid.NullUUID
}

// Auth: Manages updates to the auth system.
type AuthSchemaMigration struct {
	Version string
}

type AuthScimToken struct {
	ID            uuid.UUID
	SsoProviderID uuid.UUID
	TokenHash     string
	Prefix        string
	CreatedAt     time.Time
	ExpiresAt     sql.NullTime
	RevokedAt     sql.NullTime
	LastUsedAt    sql.NullTime
}

type AuthScimUser struct {
	ID            uuid.UUID
	SsoProviderID uuid.UUID
	UserID        uuid.NullUUID
	Resource      json.RawMessage
	UserName      string
	ExternalID    sql.NullString
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

// Auth: Stores session data associated to a user.
type AuthSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	FactorID  uuid.NullUUID
	Aal       NullAuthAalLevel
	// Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
	NotAfter      sql.NullTime
	RefreshedAt   sql.NullTime
	UserAgent     sql.NullString
	Ip            pqtype.Inet
	Tag           sql.NullString
	OauthClientID uuid.NullUUID
	// Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
	RefreshTokenHmacKey sql.NullString
	// Holds the ID (counter) of the last issued refresh token.
	RefreshTokenCounter sql.NullInt64
	Scopes              sql.NullString
}

// Auth: Manages SSO email address domain mapping to an SSO Identity Provider.
type AuthSsoDomain struct {
	ID            uuid.UUID
	SsoProviderID uuid.UUID
	Domain        string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

// Auth: Manages SSO identity provider information; see saml_providers for SAML.
type AuthSsoProvider struct {
	ID uuid.UUID
	// Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
	ResourceID sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Disabled   sql.NullBool
}

// Auth: Stores user login data within a secure schema.
type AuthUser struct {
	InstanceID               uuid.NullUUID
	ID                       uuid.UUID
	Aud                      sql.NullString
	Role                     sql.NullString
	Email                    sql.NullString
	EncryptedPassword        sql.NullString
	EmailConfirmedAt         sql.NullTime
	InvitedAt                sql.NullTime
	ConfirmationToken        sql.NullString
	ConfirmationSentAt       sql.NullTime
	RecoveryToken            sql.NullString
	RecoverySentAt           sql.NullTime
	EmailChangeTokenNew      sql.NullString
	EmailChange              sql.NullString
	EmailChangeSentAt        sql.NullTime
	LastSignInAt             sql.NullTime
	RawAppMetaData           pqtype.NullRawMessage
	RawUserMetaData          pqtype.NullRawMessage
	IsSuperAdmin             sql.NullBool
	CreatedAt                sql.NullTime
	UpdatedAt                sql.NullTime
	Phone                    sql.NullString
	PhoneConfirmedAt         sql.NullTime
	PhoneChange              sql.NullString
	PhoneChangeToken         sql.NullString
	PhoneChangeSentAt        sql.NullTime
	ConfirmedAt              sql.NullTime
	EmailChangeTokenCurrent  sql.NullString
	EmailChangeConfirmStatus sql.NullInt16
	BannedUntil              sql.NullTime
	ReauthenticationToken    sql.NullString
	ReauthenticationSentAt   sql.NullTime
	// Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
	IsSsoUser   bool
	DeletedAt   sql.NullTime
	IsAnonymous bool
}

type AuthWebauthnChallenge struct {
	ID            uuid.UUID
	UserID        uuid.NullUUID
	ChallengeType string
	SessionData   json.RawMessage
	CreatedAt     time.Time
	ExpiresAt     time.Time
}

type AuthWebauthnCredential struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	CredentialID    []byte
	PublicKey       []byte
	AttestationType string
	Aaguid          uuid.NullUUID
	SignCount       int64
	Transports      json.RawMessage
	BackupEligible  bool
	BackedUp        bool
	FriendlyName    string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	LastUsedAt      sql.NullTime
}
