// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/gofrs/uuid"
)

type Querier interface {
	CountRecoveryCodes(ctx context.Context, mfaRecoveryCodeSetID uuid.UUID) (CountRecoveryCodesRow, error)
	DeleteRecoveryCodesBySetID(ctx context.Context, mfaRecoveryCodeSetID uuid.UUID) error
	InvalidateSessionsWithAALLessThan(ctx context.Context, arg InvalidateSessionsWithAALLessThanParams) error
	LockRecoveryCodeSetByID(ctx context.Context, id uuid.UUID) (AuthMfaRecoveryCodeSet, error)
	LockRecoveryCodeSetByUserID(ctx context.Context, userID uuid.UUID) (AuthMfaRecoveryCodeSet, error)
	LockRefreshTokenForUpdate(ctx context.Context, token sql.NullString) (int64, error)
	// Locks a session row so no other transaction using FOR UPDATE can touch it.
	// SKIP LOCKED means an already-locked row surfaces as "no rows" instead of blocking.
	LockSessionForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LockUserForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LogoutAllExceptMe(ctx context.Context, arg LogoutAllExceptMeParams) error
	LogoutSession(ctx context.Context, id uuid.UUID) error
	LogoutUserSessions(ctx context.Context, userID uuid.UUID) error
	MarkRecoveryCodeConsumed(ctx context.Context, arg MarkRecoveryCodeConsumedParams) (int64, error)
	ResetRecoveryCodeSetLockout(ctx context.Context, arg ResetRecoveryCodeSetLockoutParams) (int64, error)
	RevokeOAuthSessions(ctx context.Context, arg RevokeOAuthSessionsParams) error
	RevokeTokenFamilyByParent(ctx context.Context, parent sql.NullString) error
	RevokeTokenFamilyBySessionID(ctx context.Context, sessionID uuid.NullUUID) error
	UpdateFactorAssociatedSessions(ctx context.Context, arg UpdateFactorAssociatedSessionsParams) error
	// Uses a raw UPDATE rather than the ORM's primary-key update because
	// Identity's primary key is (provider, id), not provider_id.
	UpdateIdentityProviderID(ctx context.Context, arg UpdateIdentityProviderIDParams) error
}

var _ Querier = (*Queries)(nil)
