// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
)

const countRecoveryCodes = `-- name: CountRecoveryCodes :one
SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE consumed_at IS NULL) AS remaining
FROM auth.mfa_recovery_codes WHERE mfa_recovery_code_set_id = $1
`

type CountRecoveryCodesRow struct {
	Total     int64
	Remaining int64
}

func (q *Queries) CountRecoveryCodes(ctx context.Context, mfaRecoveryCodeSetID uuid.UUID) (CountRecoveryCodesRow, error) {
	row := q.db.QueryRowContext(ctx, countRecoveryCodes, mfaRecoveryCodeSetID)
	var i CountRecoveryCodesRow
	err := row.Scan(&i.Total, &i.Remaining)
	return i, err
}

const deleteRecoveryCodesBySetID = `-- name: DeleteRecoveryCodesBySetID :exec
DELETE FROM auth.mfa_recovery_codes WHERE mfa_recovery_code_set_id = $1
`

func (q *Queries) DeleteRecoveryCodesBySetID(ctx context.Context, mfaRecoveryCodeSetID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodesBySetID, mfaRecoveryCodeSetID)
	return err
}

const lockRecoveryCodeSetByID = `-- name: LockRecoveryCodeSetByID :one
SELECT id, user_id, mfa_factor_id, failed_verification_count, verification_locked_until, created_at, updated_at
FROM auth.mfa_recovery_code_sets WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) LockRecoveryCodeSetByID(ctx context.Context, id uuid.UUID) (AuthMfaRecoveryCodeSet, error) {
	row := q.db.QueryRowContext(ctx, lockRecoveryCodeSetByID, id)
	var i AuthMfaRecoveryCodeSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MfaFactorID,
		&i.FailedVerificationCount,
		&i.VerificationLockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRecoveryCodeSetByUserID = `-- name: LockRecoveryCodeSetByUserID :one
SELECT id, user_id, mfa_factor_id, failed_verification_count, verification_locked_until, created_at, updated_at
FROM auth.mfa_recovery_code_sets WHERE user_id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) LockRecoveryCodeSetByUserID(ctx context.Context, userID uuid.UUID) (AuthMfaRecoveryCodeSet, error) {
	row := q.db.QueryRowContext(ctx, lockRecoveryCodeSetByUserID, userID)
	var i AuthMfaRecoveryCodeSet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MfaFactorID,
		&i.FailedVerificationCount,
		&i.VerificationLockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRecoveryCodeConsumed = `-- name: MarkRecoveryCodeConsumed :execrows
UPDATE auth.mfa_recovery_codes SET consumed_at = $1 WHERE id = $2 AND consumed_at IS NULL
`

type MarkRecoveryCodeConsumedParams struct {
	ConsumedAt sql.NullTime
	ID         uuid.UUID
}

func (q *Queries) MarkRecoveryCodeConsumed(ctx context.Context, arg MarkRecoveryCodeConsumedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRecoveryCodeConsumed, arg.ConsumedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetRecoveryCodeSetLockout = `-- name: ResetRecoveryCodeSetLockout :execrows
UPDATE auth.mfa_recovery_code_sets SET failed_verification_count = 0, verification_locked_until = NULL, updated_at = $1 WHERE id = $2
`

type ResetRecoveryCodeSetLockoutParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) ResetRecoveryCodeSetLockout(ctx context.Context, arg ResetRecoveryCodeSetLockoutParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetRecoveryCodeSetLockout, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
