// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/gofrs/uuid"
)

const lockRefreshTokenForUpdate = `-- name: LockRefreshTokenForUpdate :one
SELECT id FROM auth.refresh_tokens WHERE token = $1 LIMIT 1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockRefreshTokenForUpdate(ctx context.Context, token sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockRefreshTokenForUpdate, token)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const revokeTokenFamilyByParent = `-- name: RevokeTokenFamilyByParent :exec
WITH RECURSIVE token_family AS (
    SELECT rt.id, rt.user_id, rt.token, rt.revoked, rt.parent FROM auth.refresh_tokens rt WHERE rt.parent = $1
    UNION
    SELECT r.id, r.user_id, r.token, r.revoked, r.parent FROM auth.refresh_tokens r INNER JOIN token_family t ON t.token = r.parent
)
UPDATE auth.refresh_tokens r SET revoked = true FROM token_family WHERE token_family.id = r.id
`

func (q *Queries) RevokeTokenFamilyByParent(ctx context.Context, parent sql.NullString) error {
	_, err := q.db.ExecContext(ctx, revokeTokenFamilyByParent, parent)
	return err
}

const revokeTokenFamilyBySessionID = `-- name: RevokeTokenFamilyBySessionID :exec
UPDATE auth.refresh_tokens SET revoked = true, updated_at = now() WHERE session_id = $1 AND revoked = false
`

func (q *Queries) RevokeTokenFamilyBySessionID(ctx context.Context, sessionID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, revokeTokenFamilyBySessionID, sessionID)
	return err
}
