// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"

	"github.com/gofrs/uuid"
)

const invalidateSessionsWithAALLessThan = `-- name: InvalidateSessionsWithAALLessThan :exec
DELETE FROM auth.sessions WHERE user_id = $1 AND aal < $2
`

type InvalidateSessionsWithAALLessThanParams struct {
	UserID uuid.UUID
	Aal    NullAuthAalLevel
}

func (q *Queries) InvalidateSessionsWithAALLessThan(ctx context.Context, arg InvalidateSessionsWithAALLessThanParams) error {
	_, err := q.db.ExecContext(ctx, invalidateSessionsWithAALLessThan, arg.UserID, arg.Aal)
	return err
}

const lockSessionForUpdate = `-- name: LockSessionForUpdate :one
SELECT id FROM auth.sessions WHERE id = $1 LIMIT 1 FOR UPDATE SKIP LOCKED
`

// Locks a session row so no other transaction using FOR UPDATE can touch it.
// SKIP LOCKED means an already-locked row surfaces as "no rows" instead of blocking.
func (q *Queries) LockSessionForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, lockSessionForUpdate, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockUserForUpdate = `-- name: LockUserForUpdate :one
SELECT id FROM auth.users WHERE id = $1 LIMIT 1 FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockUserForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, lockUserForUpdate, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const logoutAllExceptMe = `-- name: LogoutAllExceptMe :exec
DELETE FROM auth.sessions WHERE id != $1 AND user_id = $2
`

type LogoutAllExceptMeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) LogoutAllExceptMe(ctx context.Context, arg LogoutAllExceptMeParams) error {
	_, err := q.db.ExecContext(ctx, logoutAllExceptMe, arg.ID, arg.UserID)
	return err
}

const logoutSession = `-- name: LogoutSession :exec
DELETE FROM auth.sessions WHERE id = $1
`

func (q *Queries) LogoutSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, logoutSession, id)
	return err
}

const logoutUserSessions = `-- name: LogoutUserSessions :exec
DELETE FROM auth.sessions WHERE user_id = $1
`

func (q *Queries) LogoutUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, logoutUserSessions, userID)
	return err
}

const revokeOAuthSessions = `-- name: RevokeOAuthSessions :exec
DELETE FROM auth.sessions WHERE user_id = $1 AND oauth_client_id = $2
`

type RevokeOAuthSessionsParams struct {
	UserID        uuid.UUID
	OauthClientID uuid.NullUUID
}

func (q *Queries) RevokeOAuthSessions(ctx context.Context, arg RevokeOAuthSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeOAuthSessions, arg.UserID, arg.OauthClientID)
	return err
}

const updateFactorAssociatedSessions = `-- name: UpdateFactorAssociatedSessions :exec
UPDATE auth.sessions SET aal = $1, factor_id = NULL WHERE user_id = $2 AND factor_id = $3
`

type UpdateFactorAssociatedSessionsParams struct {
	Aal      NullAuthAalLevel
	UserID   uuid.UUID
	FactorID uuid.NullUUID
}

func (q *Queries) UpdateFactorAssociatedSessions(ctx context.Context, arg UpdateFactorAssociatedSessionsParams) error {
	_, err := q.db.ExecContext(ctx, updateFactorAssociatedSessions, arg.Aal, arg.UserID, arg.FactorID)
	return err
}
