version: "3.9"
services:
  gotrue:
    container_name: gotrue
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile.dev
    # Not sure why ports aren't working. Using host as a hack
    # ports:
    #   - "9999:9999"
    network_mode: "host"
    environment:
      - GOTRUE_DB_MIGRATIONS_PATH=/go/src/github.com/netlify/gotrue/migrations
    volumes:
      - ./:/go/src/github.com/netlify/gotrue
    command: CompileDaemon --build="make build" --directory=/go/src/github.com/netlify/gotrue --recursive=true -pattern=(.+\.go|.+\.env) -exclude=gotrue -exclude=gotrue-arm64 --command=/go/src/github.com/netlify/gotrue/gotrue
  postgres:
    image: postgres:13
    container_name: postgres
    network_mode: "host"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/hack/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
