-- alter identities id and add provider_id column 

alter table auth.identities
rename column id to provider_id;

alter table auth.identities
drop constraint identities_pkey,
add column if not exists id bigint generated by default as identity,
add primary key(id),
add constraint provider_provider_id_key unique(provider, provider_id);
